# Default values for cloudbeaver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: dbeaver/cloudbeaver
  pullPolicy: IfNotPresent
  tag: "21.3.0"

securityContext: {}

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

service:
  type: ClusterIP
  port: 8978

ingress:
  enabled: true
  hosts:
    - host: cloudbeaver.example.com
      paths:
        - path: /
  tls:
    - secretName: cloudbeaver-letsencrypt-certificate
      hosts:
        - cloudbeaver.example.com

storage:
  storageClassName: local-path
  capacity: 5G
  persistenentVolume:
    create: false
    localPath: "/opt/data/cloudbeaver"
    nodeAffinityHostName: "example-node"

resources: {}
#  requests:
#    cpu: 100m
#    memory: "128Mi"
#  limits:
#    cpu: 200m
#    memory: "256Mi"
