# Default values for cloudbeaver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: dbeaver/cloudbeaver
  pullPolicy: IfNotPresent
  tag: "21.3.0"

securityContext: {}

service:
  type: ClusterIP
  port: 8978

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cloudbeaver.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudbeaver-letsencrypt-certificate
      hosts:
        - cloudbeaver.example.com

storage:
  capacity: 5G

resources: {}
#  requests:
#    cpu: 100m
#    memory: "128Mi"
#  limits:
#    cpu: 200m
#    memory: "256Mi"
