apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wikijs.name" . }}-secret
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
type: Opaque
data:
  wikijs-password:  {{ .Values.wikijs.db.password | quote }}