apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextcloud.name" . }}-deployment
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "nextcloud.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "nextcloud.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "nextcloud.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: PUID
            value: "10000"
          - name: PGID
            value: "10000"
          - name: TZ
            value: "UTC"
          - name: NEXTCLOUD_DATA_DIR
            value: /data
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
              path: /status.php
              port: 80
              scheme: HTTP
            periodSeconds: 60
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
              path: /status.php
              port: 80
              scheme: HTTP
            periodSeconds: 60
          startupProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
              path: /status.php
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
          volumeMounts:
          {{- if .Values.storage.data.useConfStorage }}
          - name: config
            mountPath: /data
            subPath: data
          {{ else }}
          - name: data
            mountPath: /data
            subPath: data
          {{ end }}
          - name: config
            mountPath: /var/www/html
            subPath: conf
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      {{- if .Values.storage.data.useConfStorage }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "nextcloud.name" . }}-data-pvc
      {{ end }}
      - name: config
        persistentVolumeClaim:
          claimName: {{ include "nextcloud.name" . }}-config-pvc