apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextcloud.name" . }}-svc
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}