# Default values for photoprism.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: photoprism/photoprism
  pullPolicy: IfNotPresent
  tag: "20211010"

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

storage:
  config:
    storageClassName: nfs-client
    capacity: 1G
  photos:
    storageClassName: nfs-photos-client
    capacity: 100G


photoprism:
  adminPassword: QWRtaW5AMTIz
  uploadLimits: 5000 #in MB
  url: https://photos.example.com/
  mysql:
    database: mysql-svc.internal.svc.cluster.local:3306
    name: photoprism
    user: photoprism
    password: cGhvdG9wcmlzbUAxMjM=

service:
  type: ClusterIP
  port: 2342

ingress:
  enabled: true
  hosts:
    - host: photos.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: photoprism-letsencrypt-certificate
      hosts:
        - photos.example.com

resources: {}