# Default values for opencart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: bitnami/opencart
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.0.3-8"

nameOverride: ""
fullnameOverride: ""

opencart:
  https:
    enable: true
  host: cart.example.com
  postSize: 100M
  uploadSize: 100M
  database:
    host: mysql-svc.internal.svc.cluster.local
    username: opencart
    password: b3BlbmNhcnQ=
    name: opencart
    flavour: mysql
  smtp:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: cGFzc3dvcmQ=

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.org/client-max-body-size: "100m"
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cart.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: opencart-letsencrypt-certificate
      hosts:
        - cart.example.com

storage:
  claimName: external-data-pvc
  data:
    subPath: opencart/data
  storageData:
    subPath: opencart/storage

resources: {}
#  limits:
#    cpu: "500m"
#    memory: "1024Mi"
#  requests:
#    cpu: "100m"
#    memory: "512Mi"
