apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.persistenentVolume.create }}
  volumeName: {{ include "homebridge.name" . }}-pv
  {{ end }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.capacity | quote }}