apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "homebridge.name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity | quote }}