apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jackett.name" . }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.config.persistenentVolume.create }}
  volumeName: {{ include "jackett.name" . }}-config-pv
  {{ end }}
  storageClassName: {{ .Values.storage.config.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.config.capacity | quote }}
---
{{- if not .Values.storage.data.useConfStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jackett.name" . }}-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.data.persistenentVolume.create }}
  volumeName: {{ include "jackett.name" . }}-data-pv
  {{ end }}
  storageClassName: {{ .Values.storage.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.data.capacity | quote }}
{{- end }}