apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.name" . }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.config.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.config.capacity | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photoprism.name" . }}-photos-pvc
  annotations:
    nfs.io/storage-path: "Photos"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.media.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.media.capacity | quote }}