apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photoprism.name" . }}-secret
  labels:
    {{- include "photoprism.labels" . | nindent 4 }}
type: Opaque
data:
  photoprism-admin-password:  {{ .Values.photoprism.adminPassword | quote }}
  photoprism-mysql-password:  {{ .Values.photoprism.mysql.password | quote }}