# Default values for changedetection.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: linuxserver/changedetection.io
  pullPolicy: IfNotPresent
  tag: "0.44.20230719"
playwrightChrome:
  image:
    repository: browserless/chrome
    tag: 1-chrome-stable-112.0.5615.49

securityContext: {}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: changedetection.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: changedetection-letsencrypt-certificate
      hosts:
        - changedetection.example.com

storage:
  capacity: 5G

resources: {}
#  requests:
#    cpu: 100m
#    memory: "128Mi"
#  limits:
#    cpu: 200m
#    memory: "256Mi"
