# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hostNetwork: true

image:
  repository: homeassistant/home-assistan
  pullPolicy: IfNotPresent
  tag: "2022.3.5"

probe:
  enable: "true"

service:
  type: ClusterIP
  port: 8123

storage:
  storageClassName: local-path
  capacity: 5G
  persistenentVolume:
    create: false
    localPath: "/opt/data/homeassistant"
    nodeAffinityHostName: "example-node"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: homeassistant.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            servicePort: 8123
  tls:
    - secretName: homeassistant-letsencrypt-certificate
      hosts:
        - homeassistant.example.com

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi