replicaCount: 1

image:
  repository: tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: "v2.7.5"

securityContext: {}

service:
  type: ClusterIP
  port: 8181

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

storage:
  storageClassName: local-path
  capacity: 1G
  persistenentVolume:
    create: false
    localPath: "/opt/data/tautulli"
    nodeAffinityHostName: "example-node"

ingress:
  enabled: true
  annotations:
  hosts:
    - host: tautulli.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tautulli-letsencrypt-certificate
      hosts:
        - tautulli.example.com

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 50m
#    memory: 64Mi
