apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.name" . }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-password:  {{ .Values.keycloak.admin.password | quote }}