# Default values for huginn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: huginn/huginn
  pullPolicy: IfNotPresent
  tag: "4df1217d3055db980a04f293e28016b77826e3ca"

  
revisionHistoryLimit: 5
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  fsGroup: 33

storage:
  capacity: 1G

service:
  huginn:
    type: ClusterIP
    port: 3000


ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: agent.example.com
  tls:
    - secretName: huginn-letsencrypt-certificate
      hosts:
        - agent.example.com

resources: {}
#  requests:
#    cpu: 100m
#    memory: "256Mi"
#  limits:
#    cpu: 500m
#    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}

huginn:
  forceSSL: true
  invitationCode: c29tZXJhbmRvbWludml0YXRpb25jb2Rl
  mysql:
    host: mysql-svc.mysql
    dbname: huginn
    port: 3306 
    username: huginn
    password: aHVnaW5uQDMyMQ==
  smtp:
    domain: gmail.com
    username: user@gmail.com
    password: c210cHBhc3N3b3Jk
    server: smtp.gmail.com
    port: 587
    authentication: plain
    starttlsAuto: true
    ssl: false
    fromEmail: user2@gmail.com
