# Default values for motioneye.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ccrisan/motioneye
  pullPolicy: IfNotPresent
  tag: "master-amd64"

hostNetwork: false

storage:
  capacity: 100G

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

probe:
  enable: "true"

service:
  type: ClusterIP
  port: 8765



ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: cctv.example.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            servicePort: 80
  tls:
    - secretName: motioneye-letsencrypt-certificate
      hosts:
        - cctv.example.com

resources: {}
#  limits:
#    cpu: "1"
#    memory: "1024Mi"
#  requests:
#    cpu: "500m"
#    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
