apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.name" . }}-deployment
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      restartPolicy: Always
      containers:
        - name: {{ include "plex.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: {{ .Values.plex.server.timeZone | quote }}
            - name: ADVERTISE_IP
              value: {{ .Values.plex.advertiseIP | quote }}
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-secret
                  key: claim-ref
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
            - name: plex-companion
              containerPort: 8324
              protocol: TCP
            - name: dlna
              containerPort: 32469
              protocol: TCP
            - name: dlna-udp
              containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: movies
              mountPath: /movies
              subPath: Movies
            - name: tv-shows
              mountPath: /tv-shows
              subPath: TVSeries
            - name: config
              mountPath: /config
              subPath: plex
            - name: transcode-volume
              mountPath: /
          {{- if .Values.probe.enable }}
          readinessProbe:
            httpGet:
              path: /identity
              port: 32400
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /identity
              port: 32400
            failureThreshold: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /identity
              port: 32400
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
      volumes:
        - name: movies
          persistentVolumeClaim:
            claimName: {{ include "plex.name" . }}-movies-pvc
        - name: tv-shows
          persistentVolumeClaim:
            claimName: {{ include "plex.name" . }}-tv-shows-pvc
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "plex.name" . }}-config-pvc
        - name: transcode-volume
          emptyDir: { }