apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plex.name" . }}-secret
  labels:
    {{- include "plex.labels" . | nindent 4 }}
type: Opaque
stringData:
  claim-ref: {{ .Values.plex.claimRef | quote }}