apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tautulli.name" . }}-deployment
  labels:
    {{- include "tautulli.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tautulli.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "tautulli.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "tautulli.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: UTC
          volumeMounts:
            - name: config
              mountPath: /config
              {{- if .Values.storage.config.subPath }}
              subPath: {{ .Values.storage.config.subPath }}
              {{- end }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.storage.config.claimName }}