# Default values for plex.

replicaCount: 1
revisionHistoryLimit: 5
image:
  repository: plexinc/pms-docker
  tag: 1.23.6.4881-e2e58f321
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostNetwork: true

plex:
  claimRef: # https://www.plex.tv/claim/
  advertiseIP: 192.168.1.1
  server:
    timeZone: "UTC"

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: false

service:
  type: ClusterIP
  port: 32400

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: plex.example.com
      paths:
      - path: /
        pathType: Prefix
  tls:
    - secretName: plex-letsencrypt-certificate
      hosts:
        - plex.example.com

resources: {}
#  limits:
#    cpu: "1"
#    memory: "2048Mi"
#  requests:
#    cpu: "500m"
#    memory: "1024Mi"

storage:
  config:
    storageClassName: local-path
    capacity: 1G
    persistenentVolume:
      create: false
      localPath: "/opt/data/plex/conf"
      nodeAffinityHostName: "example-node"
  media:
    storageClassName: local-path
    capacity: 1G
    persistenentVolume:
      create: true
      localPath: "/opt/data/plex/media"
      nodeAffinityHostName: "example-node"

tolerations: []

affinity: {}