apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pi-gallery2.name" . }}-config-pv
  finalizers: []
  labels:
    {{- include "pi-gallery2.labels" . | nindent 4 }}
spec:
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  claimRef:
    name: {{ include "pi-gallery2.name" . }}-config-pvc
    namespace: {{ .Release.Namespace }}
  local:
    path: {{ .Values.storage.configDir }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.storage.affirmative.nodeName }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pi-gallery2.name" . }}-data-pv
  finalizers: []
  labels:
    {{- include "pi-gallery2.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  claimRef:
    name: {{ include "pi-gallery2.name" . }}-data-pvc
    namespace: {{ .Release.Namespace }}
  local:
    path: {{ .Values.storage.dataDir }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.storage.affirmative.nodeName }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pi-gallery2.name" . }}-image-pv
  finalizers: []
  labels:
    {{- include "pi-gallery2.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-class
  claimRef:
    name: {{ include "pi-gallery2.name" . }}-image-pvc
    namespace: {{ .Release.Namespace }}
  local:
    path: {{ .Values.storage.imageDir }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.storage.affirmative.nodeName }}