apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudbeaver.name" . }}-deployment
  labels:
    {{- include "cloudbeaver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "cloudbeaver.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "cloudbeaver.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "cloudbeaver.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/cloudbeaver/workspace
              subPath: {{ include "cloudbeaver.name" . }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "cloudbeaver.name" . }}-pvc