apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.name" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-root-password: {{ .Values.postgres.password | quote }}