apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgres.name" . }}-statefuleset
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "postgres.name" . }}-svc
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "postgres.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "postgres.name" . }}-secret
                key: {{ include "postgres.name" . }}-root-password
          - name: POSTGRES_USER
            value: {{ .Values.postgres.user }}
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports:
          - name: postgres
            containerPort: {{ .Values.service.port }}
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
            subPath: {{ include "postgres.name" . }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "postgres.name" . }}-pvc