# Default values for wikijs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: requarks/wiki
  pullPolicy: IfNotPresent
  tag: "canary-2.5.243"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.org/client-max-body-size: "50m"
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: wiki.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wikijs-letsencrypt-certificate
      hosts:
        - wiki.example.com

storage:
  capacity: 15G

wikijs:
  db:
    host: postgres-svc
    port: 5432
    username: wikijs
    password: d2lraWpzQDMyMQ==
    name: wikijs
  admin:
    email: admin@example.com
    password: YWRtaW5AMzIx