# Default values for homebridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hostNetwork: true

image:
  repository: oznu/homebridge
  pullPolicy: IfNotPresent
  tag: "ubuntu"

probe:
  enable: "true"

service:
  type: ClusterIP
  port: 8581

storage:
  data:
    claimName: internal-data-pvc
    subPath: homebridge

homebridge:
  puid: "1000"
  pgid: "1000"
  configUI: "1"
  timezone: "UTC"


certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: homebridge.example.com
      paths:
        - path: /
          backend:
            servicePort: 80
  tls:
    - secretName: homebridge-letsencrypt-certificate
      hosts:
        - homebridge.example.com

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi