apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "huginn.name" . }}-upload-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity | quote }}