apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huginn.name" . }}-secret
  labels:
    {{- include "huginn.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.huginn.mysql.password | quote }}
  smtp-password: {{ .Values.huginn.smtp.password | quote }}
  invitation-code: {{ .Values.huginn.invitationCode | quote }} 