apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipsec.name" . }}-secret
  labels:
    {{- include "ipsec.labels" . | nindent 4 }}
type: Opaque
data:
  ipsec_psk: {{ .Values.ipsec.psk }}
  ipsec_user: {{ .Values.ipsec.user }}
  ipsec_password: {{ .Values.ipsec.password }}
  ipsec_additional_user: {{ .Values.ipsec.additional.user }}
  ipsec_additional_pass: {{ .Values.ipsec.additional.password }}