apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipsec.name" . }}-esp-udp-svc
  labels:
    {{- include "ipsec.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: esp-udp
      protocol: UDP
      port: 4500
      targetPort: 4500
  selector:
    {{- include "ipsec.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipsec.name" . }}-isakmp-udp-svc
  labels:
    {{- include "ipsec.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: isakmp-udp
      protocol: UDP
      port: 500
      targetPort: 500
  selector:
    {{- include "ipsec.selectorLabels" . | nindent 4 }}