replicaCount: 1

image:
  repository: adguard/adguardhome
  pullPolicy: IfNotPresent
  tag: "v0.107.0-b.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostNetwork: true

storage:
  capacity: 5G

securityContext: {}

service:
  type: ClusterIP
  port: 8010

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: dns.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: adguard-letsencrypt-certificate
      hosts:
        - dns.example.com

resources: {}
#  limits:
#    cpu: "100m"
#    memory: "128Mi"
#  requests:
#    cpu: "50m"
#    memory: "64Mi"

affinity: {}
