apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefly.name" . }}-deployment
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
    {{ include "firefly.selectorLabels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "firefly.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "firefly.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "firefly.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.firefly.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: DB_CONNECTION
            value: mysql
          - name: DB_HOST
            value: {{ .Values.mysql.host }}
          - name: DB_PORT
            value: {{ .Values.mysql.port | quote }}
          - name: DB_DATABASE
            value: {{ .Values.mysql.dbname }}
          - name: DB_USERNAME
            value: {{ .Values.mysql.username }}
          - name: USE_PROXIES
            value: 127.0.0.1
          - name: TRUSTED_PROXIES
            value: "**"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: mysql-password
          - name: APP_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: app-key
          - name: TZ
            value: "UTC"
          - name: MAIL_MAILER
            value: smtp
          - name: MAIL_HOST
            value: {{ .Values.mail.host }}
          - name: MAIL_PORT
            value: {{ .Values.mail.port | quote }}
          - name: MAIL_FROM
            value: {{ .Values.mail.from }}
          - name: MAIL_USERNAME
            value: {{ .Values.mail.username }}
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: mail-password
          - name: MAIL_ENCRYPTION
            value: {{ .Values.mail.encryption }}
          - name: ENABLE_EXTERNAL_MAP
            value: "true"
          - name: MAPBOX_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: mapbox-api-key
          - name: ALLOW_WEBHOOKS
            value: "true"
          volumeMounts:
          - name: upload
            mountPath: /var/www/html/storage/upload
            subPath: {{ include "firefly.name" . }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: upload
        persistentVolumeClaim:
          claimName: {{ include "firefly.name" . }}-upload-pvc
