{{- if .Values.firefly.importer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefly.name" . }}-importer-deployment
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
    {{ include "fireflyimporter.selectorLabels" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "fireflyimporter.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "fireflyimporter.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "firefly.name" . }}-importer
          image: "{{ .Values.importer.image.repository }}:{{ .Values.importer.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.importer.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: FIREFLY_III_URL
            value: "https://{{ (index .Values.ingress.hosts 0).host }}"
          - name: VANITY_URL
            value: "https://{{ (index .Values.ingress.hosts 0).host }}"
          - name: FIREFLY_III_CLIENT_ID
            value: {{ .Values.firefly.clientid | quote }}
          - name: USE_PROXIES
            value: 127.0.0.1
          - name: TRUSTED_PROXIES
            value: "**"
          - name: NORDIGEN_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: nordigen-id
          - name: NORDIGEN_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: nordigen-key
          - name: SPECTRE_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: spectre-appid
          - name: SPECTRE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: spectre-secret
          - name: AUTO_IMPORT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "firefly.name" . }}-secret
                key: auto-import-secret
          - name: CAN_POST_FILES
            value: "true"
          - name: CAN_POST_AUTOIMPORT
            value: "true"
          - name: IMPORT_DIR_WHITELIST
            value: "/var/www/html/storage/autoimport/autoImport"
          - name: TZ
            value: "UTC"
          volumeMounts:
            - name: upload
              mountPath: /var/www/html/storage/autoimport
              subPath: {{ include "firefly.name" . }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      volumes:
      - name: upload
        persistentVolumeClaim:
          claimName: {{ include "firefly.name" . }}-upload-pvc
{{- end }}