apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.name" . }}-secret
  labels:
    {{- include "firefly.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mysql.password | quote }}
  nordigen-id: {{ .Values.nordigen.id | quote }}
  nordigen-key: {{ .Values.nordigen.key | quote }} 
  spectre-appid: {{ .Values.spectre.appid | quote }} 
  spectre-secret: {{ .Values.spectre.secret | quote }} 
  app-key: {{ .Values.firefly.key | quote }} 
  mail-password: {{ .Values.mail.password | quote }}