apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencart.name" . }}-secret
  labels:
    {{- include "opencart.labels" . | nindent 4 }}
type: Opaque
data:
  OPENCART_DATABASE_PASSWORD: {{ .Values.opencart.database.password | quote }}
  OPENCART_SMTP_PASSWORD: {{ .Values.opencart.smtp.password | quote }}
