# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
revisionHistoryLimit: 5

image:
  repository: mysql
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8.0.27"

mysql:
  rootPassword: dG9vcg==

storage:
  storageClassName: local-path
  capacity: 15G
  persistenentVolume:
    create: false
    localPath: "/opt/data/mysql"
    nodeAffinityHostName: "example-node"

securityContext: {}

service:
  type: ClusterIP
  port: 3306


resources: {}
#  requests:
#    cpu: "1"
#    memory: "2048Mi"
