{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "adguard.name" . }}-certificate
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  {{- range .Values.ingress.tls }}
  dnsNames:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
  secretName: {{ .secretName }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certManager.clusterIssuer.issuerRef }}
{{- end }}