apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.name" . }}-svc
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
---
{{- if not .Values.hostNetwork -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.name" . }}-dns-svc
  labels:
    {{- include "adguard.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-53-udp
      protocol: UDP
      name: dns-53-udp
  selector:
    {{- include "adguard.selectorLabels" . | nindent 4 }}
{{- end }}