{{- if .Values.allowEgressPorts }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "application.name" . }}-egress-allowed-ports
spec:
  podSelector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - ports:
      {{- range ( split ", " .Values.allowEgressPorts ) }}
      - port: {{ . }}
      {{- end }}
{{- end }}