apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      containers:
      {{- if .Values.application }}
      {{- range $containerName, $containerValues :=  .Values.application }}
      - name: {{ $containerName }}
        image: "{{ $containerValues.image.repository }}:{{ $containerValues.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $containerValues.image.pullPolicy }}
        envFrom:
        {{- if $containerValues.configs}}
        - configMapRef:
            name: {{ include "application.name" $ }}-{{ $containerName }}
        {{- end }}
        {{- if $containerValues.secrets }}
        - secretRef:
            name: {{ include "application.name" $ }}-{{ $containerName }}
        {{- end }}
        {{- if not $.Values.hostNetwork }}
        {{- if $containerValues.services }}
        ports:
        {{- range $serviceName, $serviceValue :=  $containerValues.services }}
          - name: {{ $serviceName }}
            containerPort: {{ $serviceValue.port }}
            protocol: {{ $serviceValue.proto | default "TCP" }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if $containerValues.overrideProbe }}
        {{- with $containerValues.overrideProbe }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        {{- range $serviceName, $serviceValue :=  $containerValues.services }}
        {{- if and $serviceValue.probe $serviceValue.probe.enable }}
        readinessProbe:
          tcpSocket:
            port: {{ $serviceValue.port }}
          initialDelaySeconds: {{ $serviceValue.probe.initialDelay }}
          periodSeconds: {{ $serviceValue.probe.period }}
        livenessProbe:
          tcpSocket:
            port: {{ $serviceValue.port }}
          initialDelaySeconds: {{ $serviceValue.probe.initialDelay }}
          periodSeconds: {{ $serviceValue.probe.period }}
        startupProbe:
          tcpSocket:
            port: {{ $serviceValue.port }}
          initialDelaySeconds: {{ $serviceValue.probe.initialDelay }}
          periodSeconds: {{ $serviceValue.probe.period }}
        {{- break }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if $containerValues.volumes }}
        volumeMounts:
        {{- range $volumeName, $volumeValue :=  $containerValues.volumes }}
          - name: {{ $volumeName }}
            mountPath: {{ $volumeValue.mountPath }}
            subPath: {{ $volumeValue.subPath }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml $containerValues.resources | nindent 10 }}
        securityContext:
          {{- toYaml $containerValues.securityContext | nindent 10 }}
      {{- end }}
      {{- end }}
      volumes:
      {{- if .Values.application }}
      {{- range $containerName, $containerValues :=  .Values.application }}
      {{- if $containerValues.volumes }}
      {{- range $volumeName, $volumeValue :=  $containerValues.volumes }}
        - name: {{ $volumeName }}
          persistentVolumeClaim:
            claimName: {{ include "application.name" $ }}-{{ $containerName }}-{{ $volumeName }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}