apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.application.hostNetwork }}
      hostNetwork: {{ .Values.application.hostNetwork }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        {{- if .Values.application.configs}}
        - configMapRef:
            name: {{ include "application.name" . }}
        {{- end }}
        {{- if .Values.application.secrets }}
        - secretRef:
            name: {{ include "application.name" . }}
        {{- end }}
        {{- if not .Values.application.hostNetwork }}
        ports:
        {{- range $key, $value :=  .Values.application.ports }}
          - name: {{ $key }}
            containerPort: {{ $value.port }}
            protocol: {{ $value.proto | default "TCP" }}
        {{- end }}
        {{- end }}
        {{- if .Values.overrideProbe }}
        {{- with .Values.overrideProbe }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- else }}
        {{- range $key, $value :=  .Values.application.ports }}
        {{- if and $value.probe $value.probe.enable }}
        readinessProbe:
          tcpSocket:
            port: {{ $value.port }}
          initialDelaySeconds: {{ $value.probe.initialDelay }}
          periodSeconds: {{ $value.probe.period }}
        livenessProbe:
          tcpSocket:
            port: {{ $value.port }}
          initialDelaySeconds: {{ $value.probe.initialDelay }}
          periodSeconds: {{ $value.probe.period }}
        startupProbe:
          tcpSocket:
            port: {{ $value.port }}
          initialDelaySeconds: {{ $value.probe.initialDelay }}
          periodSeconds: {{ $value.probe.period }}
        {{- break }}
        {{- end }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- range $key, $value :=  .Values.application.volumes }}
          - name: {{ $key }}
            mountPath: {{ $value.mountPath }}
            subPath: {{ $value.subPath }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- range $key, $value :=  .Values.application.volumes }}
        - name: {{ $key }}
          persistentVolumeClaim:
            claimName: {{ include "application.name" $ }}-{{ $key }}-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}