{{- if .Values.denyEgress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "application.name" . }}-egress
spec:
  podSelector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.43.0.0/24
{{- end }}