{{- if .Values.containers }}
{{- range $containerName, $containerValues :=  .Values.containers }}
{{- if $containerValues.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" $ }}-{{ $containerName }}
spec:
  refreshInterval: "15s"
  {{- if and $containerValues.externalSecrets $containerValues.externalSecrets.secretStoreRef }}
  {{- with $containerValues.externalSecrets.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  target:
    name: {{ include "application.name" $ }}-{{ $containerName }}
  data:
    {{- range $secretName, $secretValues :=  $containerValues.externalSecrets.secrets }}
    - secretKey: {{ $secretName }}
      remoteRef:
        key: {{ $containerValues.externalSecrets.remoteRef }}
        property: {{ $secretValues }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}