{{- if .Values.containers }}
{{- range $containerName, $containerValues :=  .Values.containers }}
{{- if $containerValues.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.name" $ }}-{{ $containerName }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $secretKey, $secretValue :=  $containerValues.secrets }}
  {{ $secretKey }}: {{ $secretValue | b64enc | toYaml | indent 4 | trim }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.initContainers }}
{{- range $containerName, $containerValues :=  .Values.initContainers }}
{{- if $containerValues.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.name" $ }}-{{ $containerName }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $secretKey, $secretValue :=  $containerValues.secrets }}
    {{ $secretKey }}: {{ $secretValue | b64enc | toYaml | indent 4 | trim }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}