{{ if .Values.application.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.name" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value :=  .Values.application.secrets }}
  {{ $key }}: {{ $value | b64enc | toYaml | indent 4 | trim }}
  {{- end }}
{{ end }}