{{- if .Values.application -}}
{{- range $containerName, $containerValues :=  .Values.application }}
{{- if $containerValues.services -}}
{{- range $serviceName, $serviceValues :=  $containerValues.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.name" $ }}-{{ $containerName }}-{{ $serviceName }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
spec:
  type: {{ $serviceValues.serviceType | default "ClusterIP"}}
  {{- if $serviceValues.externalTrafficPolicy }}
  externalTrafficPolicy: {{ $serviceValues.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - port: {{ $serviceValues.port }}
      targetPort: {{ $serviceName }}
      protocol: {{ $serviceValues.proto | default "TCP" }}
      name: {{ $serviceName }}
  selector:
    {{- include "application.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}