apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeassistant.name" . }}-deployment
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
        - name: {{ include "homeassistant.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: TZ
            value: "UTC"
          - name: PGID
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          {{- if .Values.probe.enable }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: homeassistant
      securityContext:
        {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homeassistant.name" . }}-pvc