apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission.name" . }}-secret
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.transmission.username | quote }}
  password: {{ .Values.transmission.password | quote }}