replicaCount: 1

image:
  repository: linuxserver/radarr
  pullPolicy: IfNotPresent
  tag: "3.2.2"

securityContext: {}

service:
  type: ClusterIP
  port: 7878

storage:
  storageClassName: local-path
  capacity: 1G
  persistenentVolume:
    create: false
    localPath: "/opt/data/radarr"
    nodeAffinityHostName: "example-node"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: radarr.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: radarr-letsencrypt-certificate
      hosts:
        - radarr.example.com

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 50m
#    memory: 64Mi
