# Default values for nextcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: nextcloud
  pullPolicy: IfNotPresent
  tag: "22.0.0-apache"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  fsGroup: 33

storage:
  config:
    storageClassName: local-path
    capacity: 1G
    persistenentVolume:
      create: false
      localPath: "/opt/data/plex/conf"
      nodeAffinityHostName: "example-node"
  data:
    useConfStorage: false
    storageClassName: local-path
    capacity: 15G
    persistenentVolume:
      create: false
      localPath: "/opt/data/plex/media"
      nodeAffinityHostName: "example-node"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: files.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextcloud-letsencrypt-certificate
      hosts:
        - files.example.com

resources: {}
#  requests:
#    cpu: 100m
#    memory: "256Mi"
#  limits:
#    cpu: 500m
#    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
