# Default values for nextcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: nextcloud
  pullPolicy: IfNotPresent
  tag: "22.0.0-apache"

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  fsGroup: 33

storage:
  config:
    claimName: internal-data-pvc
    subPath: nextcloud
  data:
    claimName: internal-media-pvc
    subPath: FilesCloudDrive

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
  hosts:
    - host: files.example.com
      paths:
        - path: /
  tls:
    - secretName: nextcloud-letsencrypt-certificate
      hosts:
        - files.example.com

resources: {}
#  requests:
#    cpu: 100m
#    memory: "256Mi"
#  limits:
#    cpu: 500m
#    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
