apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timemachine.name" . }}-secret
  labels:
    {{- include "timemachine.labels" . | nindent 4 }}
type: Opaque
data:
  timemachine-password:  {{ .Values.timeMachine.password | quote }}