# Default values for timemachine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: true
image:
  repository: mbentley/timemachine
  pullPolicy: IfNotPresent
  tag: "smb-20211019"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  config:
    storageClassName: local-path
    capacity: 1G
    persistenentVolume:
      create: false
      localPath: "/opt/data/timemachine/conf"
      nodeAffinityHostName: "example-node"
  data:
    storageClassName: local-path
    capacity: 15G
    persistenentVolume:
      create: false
      localPath: "/opt/data/timemachine/media"
      nodeAffinityHostName: "example-node"

timeMachine:
  advertisedHostname: ""
  custom:
    smb:
      conf: "false"
    user: "false"
    debugLevel: "1"
  mimicModel: "TimeCapsule8,119"
  externalConf: ""
  hideShares: "no"
  userName: "timemachine"
  groupName: timemachine
  password: "dGltZW1hY2hpbmU="
  uid: "1000"
  gid: "1000"
  setPermissions: "false"
  shareName: "TimeMachine"
  workgroup: "WORKGROUP"
  smb:
    inheritPermission: "no"
    nfsAces: "yes"
    metadata: "stream"
    port: "445"
    vfsPbjects: "acl_xattr fruit streams_xattr"
  volumeSizeLimit: "0"

resources: {}
