# Default values for timemachine.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: true
image:
  repository: mbentley/timemachine
  pullPolicy: IfNotPresent
  tag: "smb-20211019"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  conf:
    claimName: internal-data-pvc
    samba:
      subPath: timemachine/samba/run
      cache:
        subPath: timemachine/samba/cache
      lib:
        subPath: timemachine/samba/lib
  data:
    claimName: internal-timemachine-backup-pvc
    subPath:

timeMachine:
  advertisedHostname: ""
  custom:
    smb:
      conf: "false"
    user: "false"
    debugLevel: "1"
  mimicModel: "TimeCapsule8,119"
  externalConf: ""
  hideShares: "no"
  userName: "timemachine"
  groupName: timemachine
  password: "dGltZW1hY2hpbmU="
  uid: "1000"
  gid: "1000"
  setPermissions: "false"
  shareName: "TimeMachine"
  workgroup: "WORKGROUP"
  smb:
    inheritPermission: "no"
    nfsAces: "yes"
    metadata: "stream"
    port: "445"
    vfsPbjects: "acl_xattr fruit streams_xattr"
  volumeSizeLimit: "0"

resources: {}
