apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitwarden.name" . }}-svc
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pms
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "bitwarden.selectorLabels" . | nindent 4 }}