nameOverride: windows
replicaCount: "1"
component: "windows-desktop"
hostNetwork: false
denyEgress: false
containers:
  windows:
    image:
      repository: "dockurr/windows"
      tag: "4.01"
      pullPolicy: "IfNotPresent"
    configs:
      VERSION: "11"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
    securityContext:
      privileged: true
    services:
      win-rdp-tcp:
        port: 3089
        probe:
          enable: false
      win-rdp-udp:
        port: 3089
        proto: UDP
        probe:
          enable: false
      win-http:
        port: 8086
        probe:
          enable: false
        ingress:
        - enable: true
          host: win.int.chynten.com
          path: /
          pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            kubernetes.io/ingress.class: nginx
    volumes:
      storage:
        persistentVolumeName: win-storage
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /storage
        subPath: windows/storage
        capacity: 5G
      dev-kvm:
        persistentVolumeName: dev-kvm-pv
        hostPath: /dev/kvm
        mountPath: /dev/kvm