nameOverride: openproject
replicaCount: "1"
component: "tv-serveaar"
hostNetwork: false
denyEgress: false
initContainers:
  openproject-seeder:
    image:
      repository: "openproject/openproject"
      tag: "14.2"
    command: [ './docker/prod/seeder' ]
    configs:
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
      RAILS_MIN_THREADS: "4"
      RAILS_MAX_THREADS: "16"
      USE_PUMA: "true"
      IMAP_ENABLED: "false"
    secrets:
      DATABASE_URL: <path:secrets/data/apps/openproject#connection_string>
    volumes:
      data-seeder:
        persistentVolumeName: data-seeder
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /var/openproject/assets
        subPath: openproject
        capacity: 5G
containers:
  openproject-web:
    image:
      repository: "openproject/openproject"
      tag: "14.2"
    command: ['./docker/prod/web']
    configs:
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
      RAILS_MIN_THREADS: "4"
      RAILS_MAX_THREADS: "16"
      USE_PUMA: "true"
      IMAP_ENABLED: "false"
    secrets:
      DATABASE_URL: <path:secrets/data/apps/openproject#connection_string>
    services:
      http:
        port: 8080
        probe:
          enable: false
        ingress:
          - enable: true
            host: project.chynten.com
            path: /
            pathType: Prefix
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              kubernetes.io/ingress.class: nginx
    volumes:
      data-web:
        persistentVolumeName: data-web
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /var/openproject/assets
        subPath: openproject
        capacity: 5G
  openproject-worker:
    image:
      repository: "openproject/openproject"
      tag: "14.2"
    command: ['./docker/prod/worker']
    configs:
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
      RAILS_MIN_THREADS: "4"
      RAILS_MAX_THREADS: "16"
      USE_PUMA: "true"
      IMAP_ENABLED: "false"
    secrets:
      DATABASE_URL: <path:secrets/data/apps/openproject#connection_string>
    volumes:
      data-worker:
        persistentVolumeName: data-worker
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /var/openproject/assets
        subPath: openproject
        capacity: 5G
  openproject-cron:
    image:
      repository: "openproject/openproject"
      tag: "14.2"
    command: ['./docker/prod/cron']
    configs:
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: ""
      RAILS_MIN_THREADS: "4"
      RAILS_MAX_THREADS: "16"
      USE_PUMA: "true"
      IMAP_ENABLED: "false"
    secrets:
      DATABASE_URL: <path:secrets/data/apps/openproject#connection_string>
    volumes:
      data-cron:
        persistentVolumeName: data-cron
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /var/openproject/assets
        subPath: openproject
        capacity: 5G