replicaCount: 1

component: dns-server
managedBy: chynten
hostNetwork: false
dnsConfig:
  nameserver: 10.0.0.0
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
extraLabels:
  tags.datadoghq.com/env: prod
application:
  container1:
    image:
      repository: adguard/adguardhome
      pullPolicy: IfNotPresent
      tag: "v0.107.0-b.5"
    configs:
      ENV1: VAR1
      ENV2: VAR2
    externalSecrets:
      secretStoreRef:
        name: hashicorp-vault-store
        kind: ClusterSecretStore
    secrets:
      secret1: value1
      secret2: value2
    services:
      http:
        port: 8978
        probe:
          enable: true
        ingress:
          enable: true
          host: db.int.chynten.com
          path: /
          pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            kubernetes.io/ingress.class: nginx
    volumes:
      data:
        persistentVolumeName: cloudbeaver
        storageClassName: nfs-client
        accessMode: ReadWriteOnce
        mountPath: /opt/cloudbeaver/workspace
        subPath: cloudbeaver
        capacity: 5G
    securityContext: {}
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    overrideProbe: {}
  container2:
    image:
      repository: adguard/adguardhome
      pullPolicy: IfNotPresent
      tag: "v0.107.0-b.5"
    configs:
      ENV3: VAR3
      ENV4: "123"
    externalSecrets:
      secretStoreRef:
        name: hashicorp-vault-store
        kind: ClusterSecretStore
      remoteRef: mariadb1
      secrets:
        secret3: value3
        secret4: "123"
    secrets:
      secret3: value3
      secret4: "123"
    services:
    volumes:
      data:
        persistentVolumeName: cloudbeaver1
        storageClassName: nfs-client1
        accessMode: ReadWriteOnce
        mountPath: /opt/cloudbeaver/workspace1
        subPath: cloudbeaver1
        capacity: 5G
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
    resources: {}
    overrideProbe: {}

affinity: {}

podAnnotations: {}