apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restya.name" . }}-secret
  labels:
    {{- include "restya.labels" . | nindent 4 }}
type: Opaque
data:
  restya-password:  {{ .Values.restya.db.password | quote }}