apiVersion: v1
kind: Service
metadata:
  name: {{ include "restya.name" . }}-svc
  labels:
    {{- include "restya.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "restya.selectorLabels" . | nindent 4 }}