# wg-access-server config
config: {}

web:
  config:
    adminUsername: "admin"
    adminPassword: "admin"
    privateKey: ""
  service:
    type: ClusterIP
    annotations: {}

wireguard:
  config:
    privateKey: ""
  service:
    type: LoadBalancer
    annotations: {}

persistence:
  enabled: true
  size: 100Mi
  annotations: {}
  accessModes:
    - ReadWriteOnce
  subPath: ""

hostNetwork: true

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: vpn.example.com
    paths:
      - path: /
        pathType: Prefix
  tls:
    - secretName: adguard-letsencrypt-certificate
      hosts:
      - dns.example.com

nameOverride: ""

fullnameOverride: ""

imagePullSecrets: []

image:
  repository: linuxserver/wireguard
  pullPolicy: IfNotPresent
  tag: "v0.4.6"

# multiple replicas is only supported when using
# a supported highly-available storage backend (i.e. postgresql)
replicas: 1

strategy: {}
  # the deployment strategy type will default to "Recreate" when persistence is enabled
  # or "RollingUpdate" when persistence is not enabled.
  # type: Recreate

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
