# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hostNetwork: "false"

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "14.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432

resources: {}

postgres:
  user: postgres
  password: cG9zdGdyZXNAMTIz

storage:
  capacity: 15G
