# Default values for firefly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
hostNetwork: false
image:
  repository: fireflyiii/core
  pullPolicy: IfNotPresent
  tag: "version-5.7.12"
importer:
  image:
    repository: fireflyiii/data-importer
    pullPolicy: IfNotPresent
    tag: "version-0.9.16"
  
revisionHistoryLimit: 5
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  fsGroup: 33

storage:
  capacity: 1G

service:
  firefly:
    type: ClusterIP
    port: 8080
  importer:
    type: ClusterIP
    port: 8080

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: money.example.com
  tls:
    - secretName: firefly-letsencrypt-certificate
      hosts:
        - money.example.com

resources: {}
#  requests:
#    cpu: 100m
#    memory: "256Mi"
#  limits:
#    cpu: 500m
#    memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  host: mysql-svc.mysql
  dbname: firefly
  port: 3306 
  username: firefly
  password: ZmlyZWZseQ==
nordigen:
  id: bm9yZGlnZW5faWQ=
  key: bm9yZGlnZW4ta2V5
spectre:
  appid: c3BlY3RyZS1hcHBpZA==
  secret: c3BlY3RyZS1zZWNyZXQ=
firefly:
  clientid: 4
  key: WldqMHNXcFdaSkhBemZTdFIxZFRLQ3JVajRSZmpqRWY=