replicaCount: 1
hostNetwork: false
image:
  repository: restyaplatform/restyaboard
  pullPolicy: IfNotPresent
  tag: "v1.7"

certManager:
  enabled: true
  clusterIssuer:
    issuerRef: letsencrypt

storage:
  storageClassName: local-path
  capacity: 15G
  persistenentVolume:
    create: false
    localPath: "/opt/data/restya"
    nodeAffinityHostName: "example-node"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: pm.example.com
      paths:
        - path: /
  tls:
    - secretName: restya-letsencrypt-certificate
      hosts:
        - pm.example.com

restya:
  db:
    admin:
      username: postgres
      password: YWRtaW5AMTIz
    port: 5432
    host: postgres-svc
    username: restya
    password: cmVzdHlhQDEyMw==



resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
