apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.name" . }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.mysql.password | quote }}