apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "mysql.name" . }}-root-password: {{ .Values.mysql.rootPassword | quote }}